FROM gcc:11.2.0

# ---- 安装依赖 ----
RUN apt-get -qq update \
    && apt-get -qq install --no-install-recommends \
        git \
        cmake \
        rsync \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# ---- 安装 Google Test ----
WORKDIR /usr/src/libraries
RUN git clone --depth=1 -b main https://github.com/google/googletest.git
WORKDIR /usr/src/libraries/googletest/build
RUN cmake .. && make && make install

# ---- 工作目录 & 拷贝代码 ----
WORKDIR /usr/src/app
COPY . .

# ---- 默认执行 ----
CMD ["/bin/bash"]

